---
parser: babel-eslint
parserOptions:
  ecmaVersion: 7
  sourceType: module
  jsx: true
extends:
  - airbnb
  - plugin:react-native/all
  - eslint:recommended
  - prettier
plugins:
  - fp
  - react
  - react-native
env:
  browser: true
  node: true
globals:
  __DEV__: true
rules:
  # General
  comma-dangle: [warn, always-multiline]
  global-require: off
  key-spacing: 0
  guard-for-in: off
  consistent-return: off
  max-len: [warn, 160, 4]
  default-case: off
  no-else-return: off
  no-multi-spaces: 0
  no-underscore-dangle: 0
  no-var: error
  no-restricted-syntax: off
  import/order: error
  no-use-before-define: off
  no-param-reassign: off
  no-continue: off
  class-methods-use-this: off
  eqeqeq: warn
  no-irregular-whitespace: off
  no-unneeded-ternary: off
  no-return-assign: off
  radix: off
  no-console: off
  # FP
  fp/no-arguments: off
  fp/no-delete: error
  fp/no-events: error
  fp/no-get-set: error
  fp/no-loops: off
  no-let: off
  fp/no-mutating-assign: error
  fp/no-mutating-methods: error
  fp/no-mutation: off
  fp/no-nil: off
  fp/no-proxy: error
  fp/no-rest-parameters: error
  fp/no-this: off
  fp/no-throw: off
  fp/no-unused-expression: off
  fp/no-valueof-field: error
  # Import
  import/no-unresolved: error
  import/extensions: error
  import/no-cycle: off
  import/no-useless-path-segments: off
  import/no-extraneous-dependencies: error
  import/no-named-as-default: error
  import/prefer-default-export: off
  # React
  react/sort-comp: error
  react/jsx-no-bind: error
  react/jsx-filename-extension: off
  react/forbid-prop-types: error
  react/prop-types: off
  react/destructuring-assignment: off
  react/jsx-one-expression-per-line: off
  react/no-access-state-in-setstate: off
  react/jsx-props-no-spreading: error
  react/static-property-placement: error
  react/jsx-fragments: error
  react/state-in-constructor: error
  react/jsx-wrap-multilines: error
  # React Native
  react-native/no-inline-styles: off
  react-native/no-raw-text: error
  react/jsx-curly-newline: off
  react-native/sort-styles: off
settings:
  import/resolver:
    node:
      paths:
        - 'src/'
