# .circleci/config.yml

version: 2.1

jobs:
  build:
    macos:
      xcode: 11.4.0
    environment:
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run:
          name: Install expo cli
          command: npm install -g expo-cli
      - run:
          name: Install Turtle CLI
          command: npm install -g turtle-cli --unsafe-perm=true
      - run:
          name: Install app packages
          command: yarn install
      - run:
          name: Run turtle CLI
          command: turtle build:ios
      - run: 
          name: Xcode CLI install
          command: xcode-select --install
      - run:
          name: Xcode run
          command: xcrun altool --upload-app -f path/to/the/standalone-app.ipa -u youremail@apple.com —verbose -p <app-specific-password>
      - store_artifacts:
          path: output
